### ISSUE TITLE
未找到相关的 Issues 进行评论  请联系 @zhoufeilongjava 初始化创建

### ISSUE THREAD

**Issue by zhoufeilongjava** [gitalk/gitalk#102]
点击使用github登录后,出现 Error: Validation Failed. 

https://zhoufeilongjava.github.io

**Comment by aaron-xue** [comment]
我也出现了Error: Validation Failed，错误码是422

**Comment by booxood** [comment]
@zhoufeilongjava @aaron-xue 
一直都是吗？
可以访问 `https://cors-anywhere.herokuapp.com/` 吗？

**Comment by tiexo** [comment]
@booxood 我也遇到了
之前都是正常的，更新1.2.2后出现的？
登录状态提示

未找到相关的 Issues 进行评论
请联系 @[tiexo] 初始化创建

**Comment by zhoufeilongjava** [comment]
@booxood 可以访问

**Comment by booxood** [comment]
@tiexo 点击 `初始化创建` 会创建 issue 吗？你有登陆吗？

**Comment by tiexo** [comment]
@booxood 没有初始化按钮，是登陆状态

**Comment by booxood** [comment]
@tiexo  
![image](https://user-images.githubusercontent.com/2151410/35845324-f09753ec-0b4c-11e8-891d-5fa79810ebbf.png) 

这个配置项配错了吧

**Comment by booxood** [comment]
@zhoufeilongjava @aaron-xue 你们一直都是显示 Error: Validation Failed. 吗？

**Comment by tiexo** [comment]
@booxood 啊，没错呀，就是我的用户名。一直没改过之前都是正常的，

**Comment by tiexo** [comment]
我的好了...多谢 @booxood  
>_<|||

**Comment by hushhw** [comment]
我也显示`Error: Validation Failed.`QAQ

**Comment by igoodvegetablea** [comment]
登陆后显示Error: Validation Failed.

同时无法进行评论，评论框可以编辑

网页错误信息如下

```
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
gitalk.jsx:127 err: Error: Request failed with status code 422
    at e.exports (https://unpkg.com/gitalk@1.2.2/dist/gitalk.min.js:1:34270)
    at e.exports (https://unpkg.com/gitalk@1.2.2/dist/gitalk.min.js:19:1283)
    at XMLHttpRequest.h.(anonymous function) (https://unpkg.com/gitalk@1.2.2/dist/gitalk.min.js:1:33269)
```

**Comment by booxood** [comment]
@hushhw @igoodvegetablea @siwifttiger 可以把被返回 `422` 的这个请求的完整信息贴出来吗？

**Comment by igoodvegetablea** [comment]
似乎是
```
const query = queryParse()
    if (query.code) {
      const code = query.code
      delete query.code
      const replacedUrl = `${location.origin}${location.pathname}${queryStringify(query)}${location.hash}`
      history.replaceState(null, null, replacedUrl)
      this.options = Object.assign({}, this.options, {
        url: replacedUrl,
        id: replacedUrl
      }, props.options)

      axiosJSON.post(this.options.proxy, {
        code,
        client_id: this.options.clientID,
        client_secret: this.options.clientSecret
      }).then(res => {
        if (res.data && res.data.access_token) {
          this.accessToken = res.data.access_token

          this.getInit()
            .then(() => this.setState({ isIniting: false }))
            .catch(err => {
              console.log('err:', err)
              this.setState({
                isIniting: false,
                isOccurError: true,
                errorMsg: formatErrorMsg(err)
              })
            })
        } else {
          // no access_token
          console.log('res.data err:', res.data)
          this.setState({
            isOccurError: true,
            errorMsg: formatErrorMsg(new Error('no access token'))
          })
        }
      }).catch(err => {
        console.log('err: ', err)
        this.setState({
          isOccurError: true,
          errorMsg: formatErrorMsg(err)
        })
      })
    } else {
      this.getInit()
        .then(() => this.setState({ isIniting: false }))
        .catch(err => {
          console.log('err:', err)
          this.setState({
            isIniting: false,
            isOccurError: true,
            errorMsg: formatErrorMsg(err)
          })
        })
    }
```
query.code未被满足
[这里](http://119.28.180.127/2017/09/25/CodeForces853%E8%A7%A3%E9%A2%98%E6%8A%A5%E5%91%8A/)是问题出现的页面

**Comment by igoodvegetablea** [comment]
[这里](https://api.github.com/repos/igoodvegetablea/igoodvegetablea.github.io/issues/1)是产生错误请求的地址
[这里](http://119.28.180.127/2017/11/18/CodeForces891C%E8%A7%A3%E9%A2%98%E6%8A%A5%E5%91%8A/)是产生错误的页面之一

**Comment by hushhw** [comment]
```
{
  "message": "Validation Failed",
  "errors": [
    {
      "value": "/2018/02/03/%E2%80%9C%E5%9F%83%E6%B0%8F%E7%AD%9B%E6%B3%95%E2%80%9D%E6%80%9D%E6%83%B3%E8%BF%90%E7%94%A8/",
      "resource": "Label",
      "field": "name",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/issues/#create-an-issue"
}

```

**Comment by igoodvegetablea** [comment]
参照102的问题，发现确实是由于label太长导致的无法评论，我在短label下进行了尝试，已经可以了

**Comment by siwifttiger** [comment]
我不是很懂前端。。。不知道下面这个是不是算不算报错
```
ServiceWorker registration failed:  DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
https://api.github.com/repos/siwifttiger/siwifttiger.github.io/issues Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
gitalk.jsx:101 err: Error: Request failed with status code 422
    at e.exports (https://unpkg.com/gitalk@1.2.2/dist/gitalk.min.js:1:34270)
    at e.exports (https://unpkg.com/gitalk@1.2.2/dist/gitalk.min.js:19:1283)
    at XMLHttpRequest.h.(anonymous function) (https://unpkg.com/gitalk@1.2.2/dist/gitalk.min.js:1:33269)
```

**Comment by HuberyYang** [comment]
- 我也碰到了这个问题，研究了一下，发现是文章名称经URL编码后添加到issues的label里，但是label的长度上限是50个字符，所以文章名有些长的都会生成label失败，也就没办法评论了。
- 提一下个人想法，不知道行不行得通：文章名经URL编码后转MD5，然后再生成label,这样就不会超过长度了，也存在区分度

**Comment by SilverSpear1031** [comment]
@igoodvegetablea 我和你出现情况一模一样，希望作者能改进啊，好像以前没有这个BUG？

**Comment by PriestTomb** [comment]
@HuberyYang 你的这个思路我们自己可以在本地用 js 实现，我今天试了一下是可行的，可以参考我的 [这篇文章](https://priesttomb.github.io/%E6%97%A5%E5%B8%B8/2018/02/12/%E5%A4%84%E7%90%86Gitalk%E4%B8%AD%E7%94%B1%E4%BA%8E%E6%96%87%E7%AB%A0URL%E8%BF%87%E9%95%BF%E5%AF%BC%E8%87%B4%E7%9A%84Validation-Failed(422)/)

**Comment by HuberyYang** [comment]
@PriestTomb 确实可以了,很nice

**Comment by ashfinal** [comment]
也遇到了同样的 422 错误。
但楼上说的 label 太长无法创建，貌似站不住脚。比如我的这篇博客，长度很短，依然无法初始化。

https://macplay.github.io/posts/shu-ju-ke-shi-hua-seaborn/

**Comment by heroydx** [comment]
难道只能通过缩短title才能解决吗？QAQ

**Comment by igoodvegetablea** [comment]
@ashfinal  你可以试一下更短的label，据我实验你这个label还是长了。
或者像 @HuberyYang 说的使用md5作为label。

**Comment by mr-wind** [comment]
```
var gitalk = new Gitalk({
    clientID: '{{ theme.gitalk.ClientID }}',
    clientSecret: '{{ theme.gitalk.ClientSecret }}',
    repo: '{{ theme.gitalk.repo }}',
    owner: '{{ theme.gitalk.githubID }}',
    admin: ['{{ theme.gitalk.adminUser }}'],
    id: decodeURI(location.pathname),
    distractionFreeMode: '{{ theme.gitalk.distractionFreeMode }}'
})
gitalk.render('gitalk-container')
```

我添加了一句 **id: decodeURI(location.pathname)** 使用了JS的解码函数decodeURI()。
这样我生成issue的label貌似就是中文的字符。

然后发现如果以前有评论了的话，可以把对应的issue的label改成新生成的label（注意保证每篇文章Gitalk和该文章lebel的唯一貌似就行了）

**Comment by Mrminfive** [comment]
![2018-02-23 23_54_47- css _ minfive blog](https://user-images.githubusercontent.com/24197735/36603186-f9f26c6e-18f4-11e8-9b90-18999badfb8f.png)

短 label 同样出现 422 状态码

**Comment by PriestTomb** [comment]
@Mrminfive 你这一串其实一样超了

官方限制：

![长度限制](http://oxujjb0ls.bkt.clouddn.com/image/issue_label%E9%97%AE%E9%A2%98/issue_label_length.png)

你的文章链接：

![长度超出](http://oxujjb0ls.bkt.clouddn.com/image/issue_label%E9%97%AE%E9%A2%98/issue_label_error.png)

**Comment by PriestTomb** [comment]
@Mrminfive 不清楚什么时候的规则，我也是遇到一次这个报错之后才发现有这个限制的

**Comment by ashfinal** [comment]
确实是最近 GitHub 加的限制。我把文章标题改短之后也可以了。

希望大佬尽快修复吧，以前的文章 label 就不用动了，今后的文章全部采用唯一 ID。

**Comment by ashfinal** [comment]
啊 还是不对。这篇文章没有超过 75 个限制，也出现这样的错误了。
https://macplay.github.io/posts/shu-ju-ke-shi-hua-seaborn/
<img width="510" alt="screen shot 2018-02-24 at 8 06 51 pm" src="https://user-images.githubusercontent.com/6827900/36630252-61936c52-199e-11e8-9ac3-76a7f3afb94f.png">

**Comment by loremwalker** [comment]
对于这可以用gitment的label的传输问题做类似解决，将`gitalk.swig`中的`id`字段设置成`'<%= page.date %>'`

**Comment by DOUBIGROUP** [comment]
`String(new Date().valueOf())`
取个**时间戳**，，也完美解决，，，估计，，**标题还是不能太长**

**Comment by DOUBIGROUP** [comment]
我找到一个JavaScript MD5加密 `https://github.com/blueimp/JavaScript-MD5`
cdn主页：`http://www.bootcdn.cn/blueimp-md5/`
引入就是了
例子：`id: md5(window.location.pathname),`

**Comment by ashfinal** [comment]
@DOUBIGROUP 之前的文章评论受影响吗？不受影响的话，那我就把这个换上。
看着那么几篇文章一直都是出错状态，也是难受 (˶‾᷄ ⁻̫ ‾᷅˵)

**Comment by DOUBIGROUP** [comment]
之前的评论，，，肯定有影响。2333

**Comment by ashfinal** [comment]
@DOUBIGROUP 额 你这么一说我不敢动了。坐等作者赶紧修复吧。。。难受 😣

**Comment by booxood** [comment]
Gitalk 默认的配置 `id: location.href`，id 会被保存为 issue 的一个 label，**用来关联文章和 issue**。

Github 之前没有对 label 的长度做限制，所以创建的一些 issue 的 label 长度是可以超过 50的。

但是，前段时间 Github 增加了限制 **”label 的长度不能超过50“**，所以，导致 `location.href` 长度超过 50 的文章会初始化 issue 的时候失败。

为了解决这个问题，可以像 @DOUBIGROUP 说的那样设置 `id: md5(xxxx)`，进行 md5 加密确保唯一性和长度不超过50，**但是如果修改了 `id` 的配置，那之前创建的 issue 就无法与之前的文章关联了，因为之前文章对应的 label 是没有经过 md5 加密的值，也就无法找到对应的 issue 了**，所以，如果修改了 `id` 则需要把之前创建的 issue 的 label 都更新才行。

**Comment by ashfinal** [comment]
终于看到真人了！感谢对 gitalk label 的解释。这种事情确实没法提前预料到。

近段时间 gitalk 会考虑把 `id` 的配置更换下么？因为 `location.href` 真的很容易就超过 50 啊……楼上提出的唯一的 md5 值是个好主意。至于 `id` 更换后无法找到对应的 issue……能不能同时找 `location.href` 和 `md5` 值的 label 呢？提高下向后兼容性？谁也不想轻易丢评论不是……

不管怎样（丢评论也可以接受吧），还是希望尽快有个比较正式的解决方案。在 readme 里提一下也成。避免大家各行其是，用各种花样百出的「解决方案」，对 gitalk 的推广和使用肯定不利。

**Comment by booxood** [comment]
@ashfinal README 上示例代码那块做了修改也增加了说明。

不会修改默认值 `id: location.href`，如果修改了会导致更新后不兼容。

`能不能同时找 location.href 和 md5 值的 label 呢？提高下向后兼容性？` 这种处理可以考虑

**Comment by ashfinal** [comment]
@booxood 额，我的意思是可以多做一点。把 md5 方案在 readme/faq 里作为示例，这样能最大限度的避免用户各行其是，造成分裂。至于不修改默认值 `id: location.href` ，我觉得没问题。

**Comment by ashfinal** [comment]
关于兼容性的问题：同时从 label 里找默认的 `location.href` 以及 `id` 新设置（譬如 md5）。
若 **都没找到** ：
1. 说明没有初始化 -> 使用 `id` 设置初始化
2. 取到任意一个 -> 拉取评论列表

至于是否将 md5 作为默认方案，保持高度自由度也可以。还是优先处理兼容性比较重要 😺

**Comment by calpa** [comment]
同遇到这个问题，比如说：https://calpa.me/2018/03/04/console-log-colorful-output/ 就已经56个字了，超出 50字的限制，不能生成 issue。。。

为了避免对于旧有 issue 做成影响，其中一个解决方法是加一个判断，如果是在某个时期之后（好像是2018年3月），就利用 md5值的 label。否则，则继续用 location.href 为 id值。

这样应该是一个最快的 Hack 方法吧。。。

**Comment by ashfinal** [comment]
@calpa 聪明如你，竟然有个和我一样的留言簿 =՞ｪ ՞=
勾搭一下？ https://macplay.github.io/pages/liu-yan-ban/

**Comment by calpa** [comment]
@ashfinal 当然可以www

**Comment by calpa** [comment]
问题已经解决，具体解决思路记载在博客：
[Gitalk Error: Validation Failed. 442 報錯解決方法](https://calpa.me/2018/03/10/gitalk-error-validation-failed-442-solution/)

**Comment by qhh0205** [comment]
@loremwalker 按照你说的设置成时间戳的试了下，没生效，评论框都没了，配置如下：
![image](https://user-images.githubusercontent.com/12775142/37872261-51277b84-3036-11e8-925b-b33890bcc924.png)

**Comment by ashfinal** [comment]
前不久我花时间把 id 改成 md5 了，感谢 @DOUBIGROUP @calpa 。

至于以前的文章评论 id，我人肉给加标签了。主要是不能容忍用两套 id。还好只有 50 篇文章……

最后，当然没有丢评论啦。另外，还有个好处是 `window.location.pathname` 不依赖于域名，这样本地预览站点时也能拉取评论列表。也能在本地初始化评论，不必再跑到远端访问次页面了。

**Comment by qhh0205** [comment]
@ashfinal 我刚也换成 md5 啦，采用网上提供的 md5 js 源码，具体方法见该 issue #115 最后评论，献给小白们（当然我也是 QAQ）。

**Comment by ashfinal** [comment]
@qhh0205 嗯，md5 这个方法目前看来是最好的。

我之前折腾时，稍感蛋疼的是给 50 个 issue 人肉加 md5 标签 - - 
不过，折腾一次也算是一劳永逸了，还带来些额外好处，就不计较那么多啦 😸

**Comment by calpa** [comment]
其实加个时间判断就好了，不需要更改旧标签。。。

**Comment by qhh0205** [comment]
我有强迫症，还是喜欢统一起来😸 对于以前发布很多文章的童鞋加个判断不错，我刚上线 gitalk，所以没有任何判断，haha

**Comment by qhh0205** [comment]
看来你和我一样，强迫症重度患者，哈哈


ashfinal <notifications@github.com>于2018年3月25日 周日下午5:05写道：

**Comment by ashfinal** [comment]
@calpa 当时想了半天还是改旧标签了。不就是这个复制粘贴 50 次么？这个我最拿手啦！- -

@qhh0205 哈哈，能改还是尽量改，趁错误还少的时候改。

**Comment by loremwalker** [comment]
@qhh0205 哦，不好意思，没及时回复，你发的图片首先语法就有问题...多了一个`)`号...

**Comment by xuzhongyou** [comment]
![image](https://user-images.githubusercontent.com/16487416/38803021-8740f06c-41a0-11e8-955c-eb3ee9cc07d9.png)
一进去就这样

**Comment by xuepro** [comment]
Related Issues not found

Please contact @xuepro to initialize the comment

Login with Github

出现上面的，一点击login就一闪而过，回到文章开头，登录不进去，也没法评论啊？

**Comment by booxood** [comment]
这个由于 Github 限制 `labal` 长度不能超过50 引起的问题，上面已经提供了很多解决办法。

先锁定评论了。
