### ISSUE TITLE
Exception : UnhandledPromiseRejectionWarning: SecurityError: localStorage is not available for opaque origins

### ISSUE THREAD

**Issue by lovepoem** [gitalk/gitalk#370]
When I add Gitalk into a react project ,
```
    "react": "~16.13.0",
    "react-dom": "~16.13.0",
    "gitalk": "^1.6.2",
```
Run `npm run start `
It throws Exception:
 

```
(node:36027) UnhandledPromiseRejectionWarning: SecurityError: localStorage is not available for opaque origins
    at Window.localStorage (/Users/wx/workspace/wuhan2020.github.io/node_modules/docsite/node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
    at new GitalkComponent (/Users/wx/workspace/wuhan2020.github.io/node_modules/gitalk/dist/webpack:/gitalk.jsx:84:34)
    at processChild (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:2995:14)
    at resolve (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at Object.renderToString (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at files.forEach.file (/Users/wx/workspace/wuhan2020.github.io/node_modules/docsite/lib/generateJSONFile.js:87:38)
    at Array.forEach (<anonymous>)
    at parse (/Users/wx/workspace/wuhan2020.github.io/node_modules/docsite/lib/generateJSONFile.js:39:11)
(node:36027) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```

please see https://github.com/wuhan2020/wuhan2020.github.io/pull/471

**Comment by lovepoem** [comment]
在docsite 框架使用gitalk 时候报错

**Comment by lovepoem** [comment]
docsite升级后问题解决
